# Generated by Django 5.0.4 on 2024-09-07 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('type_name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=12)),
                ('room_type', models.ForeignKey(default='Single', on_delete=django.db.models.deletion.CASCADE, to='reservation_api.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(default='Manager', max_length=50)),
                ('guest_contact', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 0300-8108108', regex='^\\d{4}-\\d{7}$')])),
                ('in_date', models.DateField(default=django.utils.timezone.now)),
                ('out_date', models.DateField()),
                ('number_of_rooms', models.IntegerField()),
                ('room_type', models.ForeignKey(default='Single', on_delete=django.db.models.deletion.CASCADE, to='reservation_api.roomtype')),
            ],
        ),
    ]
